### ISSUE TITLE
Añadir persona

### ISSUE THREAD

**Issue by carlotiii30** [martinezmario02/KissDate#5]
La funcionalidad de añadir una persona a la lista está hecha, funciona bien, pero falta terminar: Cambiar de página cuando se añade y borrar los datos del formulario y tal.

**Comment by carlotiii30** [comment]
¿Dónde tiene más sentido que vaya al meter a un usuario a la lista? ¿A la página de inicio? ¿A la lista?

**Comment by carlotiii30** [comment]
Añadir también un mensaje de success

**Comment by martinezmario02** [comment]
He puesto que dirija a la lista y un mensaje de confirmación de que se ha insertado. Además, he añadido la función de seleccionar imagen pero aún no se guarda en el proyecto ni en la bd.
